# .github/workflows/publish.yml
name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Build package
        run: pdm build

      - name: Publish package
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.MQSS_PYPI_API_TOKEN }}
        run: pdm publish -v -u ${PYPI_USERNAME} -P ${PYPI_PASSWORD}
