name: Update docs

on:
  push:
    branches:
      - develop

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync

      - name: Build documentation
        run: |
          uv run mkdocs build

      - name: Clone MQSS Interfaces repository
        uses: actions/checkout@v4
        with:
          repository: Munich-Quantum-Software-Stack/MQSS-Interfaces
          ref: gh-pages
          path: MQSS-Interfaces
          token: ${{ secrets.MQSS_INTERFACES_DOCS_TOKEN }}

      - name: Copy documentation to MQSS Interfaces repository
        run: |
          rm -rf ../MQSS-Interfaces/qiskit/*
          mkdir -p MQSS-Interfaces/qiskit/
          cp -r build/docs/site/* ../MQSS-Interfaces/qiskit/

      - name: Commit and push changes
        run: |
          cd MQSS-Interfaces
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || git commit -m "Update MQSS Qiskit Adapter docs from GitHub Action"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MQSS_INTERFACES_DOCS_TOKEN }}
